language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: hhvm
        - php: 5.6
          env: check_cs=true
        - php: 7.0

env:
    global:
        - check_cs=false

before_script:
    - composer install --no-interaction

script:
    - ./bin/phpunit
    - if [ "$check_cs" = "true" ]; then bin/php-cs-fixer fix --config=.php_cs --dry-run --diff; fi;
