language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
          env: check_cs=true

env:
    global:
        - check_cs=false

before_script:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpunit
    - if [ "$check_cs" = "true" ]; then vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --diff; fi;
