Joli\SeoOverride\Bridge\Doctrine\Entity\Seo:
  type: embeddable
  fields:
    title:
      column: title
      type: text
      nullable: true
    description:
      column: description
      type: text
      nullable: true
    keywords:
      column: keywords
      type: text
      nullable: true
    robots:
      column: robots
      type: text
      nullable: true
    canonical:
      column: canonical
      type: text
      nullable: true
    ogTitle:
      column: og_title
      type: text
      nullable: true
    ogDescription:
      column: og_description
      type: text
      nullable: true
