Joli\SeoOverride\Bridge\Doctrine\Entity\SeoOverride:
  type: entity
  repositoryClass: Joli\SeoOverride\Bridge\Doctrine\Repository\SeoOverrideRepository
  table: joli_seo_override
  indexes:
    request_index:
      columns: [ path, domain ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      length: 255
    domain:
      type: string
      length: 255
      nullable: true
  embedded:
    seo:
      class: Joli\SeoOverride\Seo
