Joli\SeoOverride\Bridge\Doctrine\Entity\SeoOverride:
  type: entity
  repositoryClass: Joli\SeoOverride\Bridge\Doctrine\Repository\SeoOverrideRepository
  table: joli_seo_override
  indexes:
    request_index:
      columns: [ path, domain_alias ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    path:
      column: path
      type: text
    domainAlias:
      column: domain_alias
      type: string
      length: 255
      nullable: true
  embedded:
    seo:
      columnPrefix: seo
      class: Joli\SeoOverride\Bridge\Doctrine\Entity\Seo
