services:
    seo_override.data_collector:
        class: Joli\SeoOverride\Bridge\Symfony\DataCollector\SeoOverrideDataCollector
        arguments:
            - '@seo_override.manager'
        tags:
            -
                name:     data_collector
                template: '@SeoOverride/data_collector/seo-override.html.twig'
                id:       'seo-override'
        public: false
