parameters:
    seo_override.fetchers_mapping: [] # Parameter configured in the DIC extension

services:
    seo_override.debug_manager:
        class: Joli\SeoOverride\Bridge\Symfony\DataCollector\SeoManager
        decorates: seo_override.manager
        decoration_priority: -1000
        arguments:
            - '@seo_override.debug_manager.inner'
            - '%seo_override.fetchers_mapping%'
        public: false

    seo_override.data_collector:
        class: Joli\SeoOverride\Bridge\Symfony\DataCollector\SeoOverrideDataCollector
        arguments:
            - '@seo_override.manager'
        tags:
            -
                name: data_collector
                template: '@SeoOverride/data_collector/seo-override.html.twig'
                id: 'seo-override'
        public: false
