parameters:
    seo_override.domains: [] # Parameter configured in the DIC extension

services:
    seo_override.manager:
        class: Joli\SeoOverride\SeoManager
        arguments:
            - []
            - '%seo_override.domains%'

    seo_override.subscriber:
        class: Joli\SeoOverride\Bridge\Symfony\Subscriber\SeoSubscriber
        arguments:
            - '@seo_override.manager'
        tags:
            - { name: kernel.event_subscriber }

    seo_override.fetcher.in_memory:
        class: Joli\SeoOverride\Fetcher\InMemoryFetcher
        public: false
        arguments:
            - '' # Argument configured in the DIC extension
        tags:
            - { name: seo_override.fetcher, alias: in_memory, required_options: 'overrides' }

    seo_override.fetcher.php:
        class: Joli\SeoOverride\Fetcher\PhpFetcher
        public: false
        arguments:
            - '' # Argument configured in the DIC extension
            - '%kernel.debug%'
        tags:
            - { name: seo_override.fetcher, alias: php, required_options: 'include_path' }
